const data = {
    products: [
      {
        _id: '1',
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: '/images/1.png',
        price: 599,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Adiddas Fit Shirt',
        category: 'Shirts',
        image: '/images/3.png',
        price: 1299,
        countInStock: 20,
        brand: 'Adiddas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'LV Free Shirt',
        category: 'Shirts',
        image: '/images/5.png',
        price: 1220,
        countInStock: 5,
        brand: 'LV',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/8.png',
        price: 999,
        countInStock: 9,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Puma Slim Pant',
        category: 'Pants',
        image: '/images/pant3.jpeg',
        price: 1695,
        countInStock: 4,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Adiddas Fit Pant',
        category: 'Pants',
        image: '/images/pant1.png',
        price: 1399,
        countInStock: 0,
        brand: 'Adiddas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;