import bcrypt from 'bcryptjs';

const data = {
    users: [
      {
        name: 'Karthikaa Moorthy',
        email: 'karthikaa@admin.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: true,
      },
      {
        name: 'Karthikaa',
        email: 'karthikaa@user.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: false,
      },
    ],
    products: [
      {
        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: '/images/1.png',
        price: 599,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Adiddas Fit Shirt',
        category: 'Shirts',
        image: '/images/3.png',
        price: 1299,
        countInStock: 20,
        brand: 'Adiddas',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'LV Free Shirt',
        category: 'Shirts',
        image: '/images/5.png',
        price: 1220,
        countInStock: 5,
        brand: 'LV',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/8.png',
        price: 999,
        countInStock: 9,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        name: 'Puma Slim Pant',
        category: 'Pants',
        image: '/images/pant3.jpeg',
        price: 1695,
        countInStock: 4,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        name: 'Adiddas Fit Pant',
        category: 'Pants',
        image: '/images/pant1.png',
        price: 1399,
        countInStock: 0,
        brand: 'Adiddas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;